# Generated by Django 2.2.6 on 2019-10-25 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advpro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='school',
            new_name='schoo',
        ),
    ]
