# Generated by Django 2.2.6 on 2019-10-25 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advpro', '0002_auto_20191025_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='schoo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='advpro.School'),
        ),
    ]
