# Generated by Django 2.2.6 on 2019-11-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_auto_20191130_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='long',
            field=models.DecimalField(decimal_places=7, max_digits=20, null=True),
        ),
    ]
