# Generated by Django 2.2.6 on 2019-10-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingdoms', '0002_auto_20191025_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kingdom',
            old_name='region',
            new_name='reg',
        ),
    ]
